# Generated by Django 4.2.8 on 2023-12-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveloapp', '0002_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='desc',
            new_name='desc2',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='img',
            new_name='img2',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='name2',
        ),
    ]
