# Generated by Django 4.2.8 on 2023-12-24 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveloapp', '0003_rename_desc_destination_desc2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='desc2',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='img2',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='name2',
            new_name='name',
        ),
    ]
